export enum ERROR_REASONS {
  MILVUS_ADDRESS_IS_REQUIRED = 'The `address` is missing.',

  CREATE_COLLECTION_MISS_DATA_TYPE = 'The field object must contain the `data_type` property.',
  CREATE_COLLECTION_CHECK_PARAMS = 'The `fields` or `collection_name` is missing.',
  CREATE_COLLECTION_CHECK_PRIMARY_KEY = 'The fields object must contain a key named `data_type` with a value of int64 and another key named `is_primary_key` with a value of true.',
  CREATE_COLLECTION_CHECK_VECTOR_FIELD_EXIST = 'The vector field object must have a data type of either DataType.FloatVector or DataType.BinaryVector.',
  CREATE_COLLECTION_CHECK_MISS_DIM = 'Vector field object must contain the `dim` property.',
  CREATE_COLLECTION_CHECK_MISS_MAXLENGTH = 'Vector field object must contain the `max_length` property',
  CREATE_COLLECTION_CHECK_BINARY_DIM = 'The dim property of the Binary vector should be value mutiples of 8.',
  COLLECTION_NAME_IS_REQUIRED = 'The `collection_name` is missing.',
  COLLECTION_ID_IS_REQUIRED = 'The `collectionID` is missing.',
  COLLECTION_PARTITION_NAME_ARE_REQUIRED = 'The `collection_name` or the `partition_name` is missing.',

  INSERT_CHECK_FILEDS_DATA_IS_REQUIRED = 'The `fields_data` parameter must be passed as an array.',
  INSERT_CHECK_WRONG_FIELD = 'Insert fail: some field does not exist for this collection in line.',
  INSERT_CHECK_WRONG_DIM = 'Insert fail: Binary vector data length needs to be (dimension / 8).',
  INSERT_CHECK_WRONG_DATA_TYPE = 'is not supported.',

  SEARCH_MISS_VECTOR_TYPE = 'The `vector_type` should be DataType.FloatVector or DataType.BinaryVector.',
  SEARCH_NOT_FIND_VECTOR_FIELD = 'The `anns_field` was not matched in this collection.',
  SEARCH_DIM_NOT_MATCH = 'The vector dimension does not match your anns_field dimension.',
  SEARCH_PARAMS_IS_REQUIRED = 'The `search_params` must contain the `anns_field`, `metric_type`, `topk` and `params`.',
  SEARCH_ROUND_DECIMAL_NOT_VALID = 'The `round_decimal` should be an integer greater than -2 and less than 7',

  DELETE_PARAMS_CHECK = 'The `collection_name` or the `expr` is missing.',
  GET_METRIC_CHECK_PARAMS = 'The `metric_type` property is missing.',
  GET_FLUSH_STATE_CHECK_PARAMS = 'The type of the `segmentIDs` should be an array.',
  LOAD_BALANCE_CHECK_PARAMS = 'The `src_nodeID` is missing.',
  PARTITION_NAMES_IS_REQUIRED = 'partition_names is missing.',
  ALIAS_NAME_IS_REQUIRED = 'The `alias` is missing.',
  COMPACTIONID_IS_REQUIRED = 'The `compactionID` is missing.',
  USERNAME_PWD_ARE_REQUIRED = 'The `username` or `password` is missing.',
  USERNAME_IS_REQUIRED = 'The `username` is missing.',
  TIMESTAMP_PARAM_CHECK = 'type should be string (only contains number) or bigint.',
  DATE_TYPE_CHECK = 'The type of the `datetime` should be Date.',
  IMPORT_FILE_CHECK = 'The `files` is missing.',
}
